plugins:
  worker_mentions_enabled:
    default: true
    client: true
  worker_mentions_group_name:
    default: "workers"
    client: true
  worker_mentions_api:
    default: "https://daemo.org/api/project/workers/?format=json&topic_id="
    client: true
